version: '3.1'

services:
  twitter_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entripoint-initdb.d/init.sql
    command: --init-file /docker-entripoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: twitter_db
      MYSQL_ROOT_USER: root
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 12345
